/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package presentacion;

/**
 *
 * @author crazy
 */
public class DlgNuevoChat extends javax.swing.JDialog {
    
    private DlgNuevoGrupo dlgNuevoGrupo;
    
    /**
     * Creates new form DlgNuevoChat
     */
    public DlgNuevoChat(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        btnAceptarChat5 = new javax.swing.JButton();
        btnAceptarChat6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptarChat5.setBackground(new java.awt.Color(0, 51, 102));
        btnAceptarChat5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnAceptarChat5.setText("Quiero crear un chat con un amigo");
        btnAceptarChat5.setBorder(null);
        btnAceptarChat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarChat5ActionPerformed(evt);
            }
        });
        jPanel6.add(btnAceptarChat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 190, 40));

        btnAceptarChat6.setBackground(new java.awt.Color(0, 51, 102));
        btnAceptarChat6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnAceptarChat6.setText("Quiero crear un nuevo grupo");
        btnAceptarChat6.setBorder(null);
        btnAceptarChat6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarChat6ActionPerformed(evt);
            }
        });
        jPanel6.add(btnAceptarChat6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarChat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarChat5ActionPerformed

    }//GEN-LAST:event_btnAceptarChat5ActionPerformed

    private void btnAceptarChat6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarChat6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarChat6ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarChat5;
    private javax.swing.JButton btnAceptarChat6;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
